### ISSUE TITLE
We can haz properties.schema? 

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-hotspotMenu#9]
Plz? K Thnx Bai!

**Comment by moloko** [comment]
see #10 - any chance you could give it a test for us?

**Comment by hmaffin** [comment]
How do I test it if there’s no download file for it? Sorry, got brain fog J

All the best,
Helen
==================================
Helen Maffin
e-Learning Developer
hlm56@cam.ac.uk<mailto:hlm56@cam.ac.uk>
---------------------------
University of Cambridge
Finance Division
Greenwich House
Madingley Rise
Madingley Road
Cambridge, CB3 0TX
---------------------------
Tel: 01223 764659
Fax: 01223 765988
==================================

**Comment by moloko** [comment]
here's a link https://github.com/boonier/adapt-hotspot-menu/archive/sjm-hotspot-menu-updates_2017-11-23.zip

**Comment by hmaffin** [comment]
Ta! Will give it a trial as soon as I can.

**Comment by moloko** [comment]
@hmaffin sorry my bad apparently the OS authoring tool doesn't support additional menu settings (yet) so this only works in https://github.com/cgkineo/adapt_authoring/tree/production at the moment

**Comment by hmaffin** [comment]
Ahhhhhhhhhh ok, never mind!

All the best,
Helen
